# Generated by Django 2.2.28 on 2023-07-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
