# Generated by Django 2.2.28 on 2023-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
