# Generated by Django 2.2.28 on 2023-09-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_auto_20231001_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='profile',
            name='download_limit_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
