# Generated by Django 2.2.28 on 2023-06-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ArabicName',
        ),
    ]
