# Generated by Django 2.2.28 on 2023-04-14 20:40

import categories_and_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='solid_File',
            field=models.FileField(default=12, upload_to=categories_and_products.models.get_upload_to),
            preserve_default=False,
        ),
    ]
