# Generated by Django 3.2.3 on 2023-04-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_Name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='number_of_branches',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
