# Generated by Django 2.2.28 on 2023-07-23 01:07

import categories_and_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to=categories_and_products.models.upload_vendor_images),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=categories_and_products.models.upload_vendor_images),
        ),
    ]
