# Generated by Django 2.2.28 on 2023-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_remove_product_arabicname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='reach_to',
        ),
        migrations.AddField(
            model_name='product',
            name='start_from',
            field=models.FloatField(default=0),
        ),
    ]
