# Generated by Django 2.2.28 on 2023-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_auto_20230723_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.CharField(blank=True, help_text='Insert Link From Firebase Storage', max_length=250),
        ),
    ]
