# Generated by Django 3.2.3 on 2023-04-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_auto_20230411_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='image',
            new_name='background_image',
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='Vendors'),
        ),
    ]
