# Generated by Django 2.2.28 on 2023-04-14 20:48

import categories_and_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0002_product_solid_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=categories_and_products.models.upload_vendor_images),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to=categories_and_products.models.upload_vendor_images),
        ),
    ]
