# Generated by Django 2.2.28 on 2023-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0003_auto_20230617_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
