# Generated by Django 2.2.28 on 2023-05-01 03:58

import categories_and_products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0004_auto_20230414_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=categories_and_products.models.get_upload_to),
        ),
    ]
