# Generated by Django 2.2.28 on 2023-06-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0004_auto_20230617_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory_name', models.CharField(max_length=250, unique=True)),
                ('subCategory_slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Categories')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
