# Generated by Django 2.2.28 on 2023-10-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0005_auto_20231003_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='background_image',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo_image',
            field=models.CharField(blank=True, help_text='Insert Image From Firebase Storage', max_length=250),
        ),
    ]
