# Generated by Django 2.2.28 on 2023-07-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0007_auto_20230707_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
