# Generated by Django 2.2.28 on 2023-06-17 17:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories_and_products', '0006_subcategory_category'),
        ('orders', '0002_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('percentage', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_user', to=settings.AUTH_USER_MODEL, verbose_name='promo_user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_vendor', to='categories_and_products.Vendor', verbose_name='promo_vendor')),
            ],
            options={
                'verbose_name_plural': 'PromoCodes',
            },
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
