# Generated by Django 2.2.28 on 2023-07-07 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230617_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
